### ISSUE TITLE
responseType: "stream"

### ISSUE THREAD

**Issue by derappelt** [unjs/ohmyfetch#121]
Is there a plan to support response stream?
With axios I can do something like this:
```ts
const response = await axios.get(url, {
  responseType: "stream"
});
return response.data
```

How would I do this with $fetch?

**Comment by okxiaoliang4** [comment]
This https://github.com/unjs/ohmyfetch/pull/100 pr is resolve it. Try to upgrade the version

**Comment by AdrianFahrbach** [comment]
Would be nice to have some kind of documentation of this somewhere. As far as I see, this issue here is the only place where this feature is documented.

**Comment by pi0** [comment]
@AdrianFahrbach Would you have time to help on adding docs?
