### ISSUE TITLE
[question]： how to change response data with interceptor?

### ISSUE THREAD

**Issue by Developer27149** [unjs/ohmyfetch#124]
I want to use interceptor to change response data.I just want to change response format.
example:
```js
// response:
{
  data: {age: 1},
  code: 1
}
```

change to:
```js
{
  age: 1
}
```
what can I do in onResponse function? Thanks!

**Comment by motea927** [comment]
Hi, you can use [onResponse](https://github.com/unjs/ohmyfetch#onrequest-request-options-) and change `_data`
example:
```typescript
async onResponse({ response }) {
  response._data = {
    ...response._data.data
  }
},
```

**Comment by Developer27149** [comment]
@motea927 Thanks bro.
