### ISSUE TITLE
.catch(e => e.message) is different from in nuxt dev and production

### ISSUE THREAD

**Issue by Cosbgn** [unjs/ohmyfetch#129]
I'm using Nuxt3 rc11.  I have:

```
// server/api/foo.js
export default defineEventHandler(async (event) => {
    throw createError({ statusCode:400, statusMessage:"This user doesn't exist" })
}
```
And:
```
// /pages/foo.vue
const error = ref(null)
onMounted(async() {
	await $fetch("/api/foo")
	.catch(e => {
		console.log(e)
		error.value = e.message
	})
})
```

When U run the app locally if I add {{error}} in my template I correctly get `This user doesn't exist` but when I deploy I get `Bad request` - Why this difference between dev and production? Any way to get them to return the same message? Thanks.

**Comment by danielroe** [comment]
Reproduction: https://stackblitz.com/edit/github-dyqv6f

**Comment by danielroe** [comment]
I can't reproduce locally with a production build. If you can, would you provide a reproduction? In future, would you open Nuxt-specific issues in https://github.com/nuxt/framework? We can move them upstream depending on the root cause.

**Comment by cosbgn** [comment]
This was most likely related to [this](https://github.com/nuxt/nuxt/issues/24693) @danielroe - I just found my own issue looking for this. Posting it here just in case it helps someone https://github.com/nuxt/nuxt/issues/24693
