### ISSUE TITLE
Unable to send a GET request with a custom header using $fetch()

### ISSUE THREAD

**Issue by michael-mb** [unjs/ohmyfetch#130]
### Reproduction

```javascript
async function getArticles(){
    await $fetch(BASE_URL + 'api/article/', {
        headers: {
            "Accept-Language": "TEST IF IT CHANGE",
            "Authorization": "REQUEST_TOKEN"
        },
        method: 'GET',
    }).then( response => {
        console.log(response)
    }).catch(e => { console.log(e)})
}

```

### Describe the bug
When we send this request, we can see in the network tab of the browser console that the "Accept-Language" attribute changes. But it is almost impossible to add another header (like "Authorization"). This header (Authorization) is necessary to finish the development of our application.

The header is only modified when modifying the default elements such as: Accept, Accept-Encoding, Accept-Language, Connection, Host, ...

For more details see the image.

It should therefore have the possibility to add new entries.

![Capture d’écran 2022-09-26 à 10 19 34](https://user-images.githubusercontent.com/51961738/192229355-4f60126c-ad58-44ee-b8ac-9695e56ad948.png)

**Comment by danielroe** [comment]
This is likely your backend api restricting what headers can be sent to it, perhaps via `Access-Control-Request-Headers`. There is no issue in `ohmyfetch` - see https://stackblitz.com/edit/github-zd32kc?file=app.vue.

If you think there is, please provide a reproduction and I'll reopen. :pray:

**Comment by michael-mb** [comment]
HI @danielroe , I don't think that's the case. Because it works correctly with postman
![Capture d’écran 2022-09-26 à 11 12 11](https://user-images.githubusercontent.com/51961738/192239026-79e78350-80f8-48a3-a183-3f8c59c3e3b6.png)

**Comment by danielroe** [comment]
Postman is not making a CORS preflight.
