### ISSUE TITLE
How to update Pinia state in response interceptor?

### ISSUE THREAD

**Issue by hmingv** [unjs/ohmyfetch#134]
Hi everyone, I'm using JWT.

When the token expires, my API returns an Authorization in the headers.

It contains a new Token, and I need to use this new Token to replace the Token stored in pinia so that the API can be accessed normally next time.

I did and But it didn't work.

After the response interceptor is modified, it only takes effect temporarily, and the client does not change.

Also, in the response interceptor, navigateTo('') cannot be used, it is also invalid.

Excuse me, is there any way I can modify the value of Pinia in the response of the request?

![image](https://user-images.githubusercontent.com/57735185/192713295-709aacec-232f-4f06-b53b-11c07962b646.png)

![image](https://user-images.githubusercontent.com/57735185/192712046-31974087-a234-44c3-97f5-9a50bfaa62ea.png)

![image](https://user-images.githubusercontent.com/57735185/192712151-cf69c004-1827-4aa3-8298-ebb24a3d8fee.png)

**Comment by danielroe** [comment]
This is not really a question for `ohmyfetch` - next time, please do raise it as a discussion on https://github.com/nuxt/framework directly.

The answer is to get your store instance _outside_ of the interceptor, and then use it within it.

**Comment by hmingv** [comment]
> This is not really a question for `ohmyfetch` - next time, please do raise it as a discussion on https://github.com/nuxt/framework directly.
> 
> The answer is to get your store instance _outside_ of the interceptor, and then use it within it.

Thanks for your reply, but when I moved it outside the interceptor, I got the "nuxt instance unavailable" error.

I have a discussion at nuxt/framework, we can talk there if we can.

thank you very much.

https://github.com/nuxt/framework/discussions/7887
