### ISSUE TITLE
'Origin' request header missing when using useFetch in SSR => Laravel Sanctum won't work

### ISSUE THREAD

**Issue by boldenkintaro** [unjs/ohmyfetch#149]
It seems Laravel Sanctum requires the origin request header (in my case: localhost:3000) to identify the client (for CORS).
However, when using Nuxt3 with useFetch and SSR, the origin request header is completely missing. It is sent, however, when I use useFetch on my client. If I set the origin request header manually in SSR, everything works correctly.

I also tried to include all client request headers when doing SSR. But origin is still missing.
Am I doing something wrong or is this the expected behaviour? It seems I need the origin header for Laravel Sanctum and authentication to work properly, and setting it manually kinda seems like a hack to me...

**Comment by danielroe** [comment]
This may be helpful: https://v3.nuxtjs.org/getting-started/data-fetching/#isomorphic-fetch-and-fetch

**Comment by boldenkintaro** [comment]
> This may be helpful: https://v3.nuxtjs.org/getting-started/data-fetching/#isomorphic-fetch-and-fetch

Thank you for your response. I already tried using useRequestHeaders but the "origin" header is still missing.
