### ISSUE TITLE
deprecate `ohmyfetch` on npm

### ISSUE THREAD

**Issue by dword-design** [unjs/ohmyfetch#258]
### Describe the feature

Hi, I'm confused about the co-existence of `ofetch` and `ohmyfetch`, does it make sense to deprecate one and info on what is recommended to be used?

**Comment by pi0** [comment]
Thanks for reminder. Yes it was my intention to deprecate longer name (a while after nuxt 3 release) just forgot to do it

**Comment by pi0** [comment]
It is totally up to your preference! I think we might make readme here to prefer `$fetch` for more familiar xp what do you think?

**Comment by KaKi87** [comment]
I vote for keeping `ofetch` because it's the project's name, while `$` is a prefix that front-end frameworks use for their own reasons that aren't relevant here. Thanks
