### ISSUE TITLE
Question: Option to disable SSL certificate warnings

### ISSUE THREAD

**Issue by andreas83** [unjs/ohmyfetch#34]
Since i have only self signed certificates for local development it would be nice to have an option to disable ssl checks. 
Any hints highly appreciate.

**Comment by pi0** [comment]
Hi @andreas83. Sure we can think of a way to auto disable warnings but in the meantime, you might set `NODE_TLS_REJECT_UNAUTHORIZED=0` environment variable which is a Node.js built-in

**Comment by gjovanov** [comment]
Hi there,
I wasn't able to find any option to provide a CA CERT file for HTTPS cert validation.
E.g. something like this:

`const httpsAgent = new https.Agent({ ca: MY_CA_BUNDLE });`

Is this possible to do this with `ohmyfetch` and if so, how?
Thanks.

**Comment by 1nusah** [comment]
hi guys, anything like this for client side?
