### ISSUE TITLE
got error when 0.4.x is used in jest test. Error: You need to run with a version of node that supports ES Modules in the VM API.

### ISSUE THREAD

**Issue by jialu98** [unjs/ohmyfetch#35]
When upgrade to 0.4.x, the jest test gives error: Error: You need to run with a version of node that supports ES Modules in the VM API.
`You need to run with a version of node that supports ES Modules in the VM API. See https://jestjs.io/docs/ecmascript-modules

      2 |
      3 | export async function getFile() {
    > 4 |   const result = await $fetch('http://google.com');
        |                        ^
      5 |   return result;
      6 | }
      7 |

      at invariant (node_modules/jest-runtime/build/index.js:2423:11)
      at getExport (node_modules/ohmyfetch/cjs/node.cjs:1:136)
      at node_modules/ohmyfetch/cjs/node.cjs:2:47
      at getFile (src/index.js:4:24)
      at Object.<anonymous> (src/index.test.js:3:24)`

The same test works fine in 0.3.2

node v16.13.0
yarn 1.22.15
The test project is attached.
[fetch-app.zip](https://github.com/unjs/ohmyfetch/files/7664758/fetch-app.zip)

**Comment by pi0** [comment]
Hi! You need to do couple things to make it working as jest docs also mentioned:
- Remove babel transform preset
- Set type: module in package.json
- Use `exports default` for jest.config
- Use `NODE_OPTIONS=--experimental-vm-modules jest`


[fetch-app.zip](https://github.com/unjs/ohmyfetch/files/7757980/fetch-app.zip)
