### ISSUE TITLE
use $fetch in SSR leading to "Headers is not a function"

### ISSUE THREAD

**Issue by TrungRueta** [unjs/ohmyfetch#46]
I found that today after upgrade Nuxt3 to lastest, when use `$fetch` within SSR leading to error:
```
TypeError: Headers is not a constructor
    at $fetchRaw2 (file:///workspace/node_modules/ohmyfetch/dist/chunks/fetch.mjs:122:33)
    at $fetch2 (file:///workspace/node_modules/ohmyfetch/dist/chunks/fetch.mjs:158:12)
    at file:///workspace/.nuxt/dist/server/server.mjs:58925:25
    at Object.asyncData.refresh (file:///workspace/.nuxt/dist/server/server.mjs:950:52)
    at Module.useAsyncData (file:///workspace/.nuxt/dist/server/server.mjs:974:31)
    at file:///workspace/.nuxt/dist/server/server.mjs:58923:146
    at Module.withAsyncContext (/workspace/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7330:21)
    at setup (file:///workspace/.nuxt/dist/server/server.mjs:58923:95)
    at _sfc_main.setup (file:///workspace/.nuxt/dist/server/server.mjs:58982:23)
    at callWithErrorHandling (/workspace/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6650:22)
```

This error raised when request `$fetch` with option `method: 'POST'` and has `Body: {..}`. 

after research i found that issue from this 
`node_modules/ohmyfetch/dist/chunks/fetch.mjs` line `122`

```ctx.options.headers = new Headers(ctx.options.headers);```

`Headers` is undefined, but test same line i see `global.Headers` available:

```console.log('HEADER:', Headers, global.Headers)```

```HEADER: undefined [class Headers extends URLSearchParams]```.

Can you help check this issue.
Thank you for wonderful plugin!!

**Comment by TrungRueta** [comment]
@pi0 hi bro . can you help review this issue. i not get issue yesterday (before upgrade to `^3.0.0-27338323.1e98259`.

Thank you !!

**Comment by itshizhan** [comment]
same errror

**Comment by TrungRueta** [comment]
After a half of day reasearch, i think issue not come from ohmyfetch plugin. it because Nuxt3 framework mimix a version for server-side but not include `Headers` context. I create issue on Nuxt3 git

https://github.com/nuxt/framework/issues/2539

Anyone got same issue can track this issue
Sorry for failed alarm :)

**Comment by TrungRueta** [comment]
update:
Install fresh new Nuxt3, then downgrade `ohmyfetch` to v0.4.11 will work as expected. from v0.4.12 ( 4 days ago) it failed with case `POST` + `body: {}`.

**Comment by xiaojieajie** [comment]
> 更新： 安装全新的 Nuxt3，然后降级`ohmyfetch`到 v0.4.11 将按预期工作。从 v0.4.12（4 天前）开始，它失败了 case `POST`+ `body: {}`。


Indeed, I demoted to V0.4.11 and it worked

**Comment by pi0** [comment]
Issue is fixed by https://github.com/nuxt/framework/pull/2615 however we need improvement in ohmyfetch to use globals by default. 

Please consider opening nuxt related issues in nuxt/framework next time 🙏
