### ISSUE TITLE
Leverage native fetch support 

### ISSUE THREAD

**Issue by LifeIsStrange** [unjs/ohmyfetch#52]
Consider using native node fetch support instead of the library node fetch, iff benchmarks show native node fetch to outperform or equal node fetch
https://news.ycombinator.com/item?id=30161626

**Comment by pi0** [comment]
Hi @LifeIsStrange. Actually, that is the case.

> If globalThis.fetch is available, will be used instead.

ohmyfetch always prefers native global `fetch` over `node-fetch` implementation wheen available.

**Comment by LifeIsStrange** [comment]
@pi0 Thanks for the fast answer :)
