### ISSUE TITLE
[BUG] About send a request with body text type

### ISSUE THREAD

**Issue by lnbin** [unjs/ohmyfetch#58]
https://github.com/unjs/ohmyfetch/blob/5307000f12ad2414e07f194bb049d78cef654cd4/src/fetch.ts#L108-L109
If I want to send a text body post request, it will `JSON.stringify` my text and add `"` before and after my text.

![image](https://user-images.githubusercontent.com/16643744/161223917-c2aa1cfe-3bb0-4249-b4d6-1328b4febe55.png)

**Comment by pslxx** [comment]
same problem

**Comment by fsblemos** [comment]
Same here. Maybe it could have a boolean option `serialize` which defaults to true?

**Comment by P4sca1** [comment]
I think serialization should only happen, when `Content-Type` is set to `application/json` (the default).

**Comment by qyn980427** [comment]
I had the same problem
