### ISSUE TITLE
what to do when connection refused returned

### ISSUE THREAD

**Issue by leccyril** [unjs/ohmyfetch#70]
Hello,

i am trying to get the error when backend server is not connected to get the error and display it,i searched in documentation but not found

any idea?

**Comment by leccyril** [comment]
for example i have a call to rest api and then i have to modify the display, using async onRequestError does not work because the display is not modified (cause to the async) so i use a simple try catch but the reponse is not parseable ex

FetchError: 400  (http://localhost:8080/rest/enquiry/create)
    at async Proxy.handleSubmit (index.vue:343:5)

i want to retrieve the status and the message error to process the error return properly

**Comment by birdlavv** [comment]
Perhaps you could do something like this:

```typescript
import { $fetch } from 'ohmyfetch'

const options = {
    // optional auth headers and such
}
const { data, status } = await $fetch.raw('http://httpbin.org/status/404', { ...options })
    .then((response) => ({ data: response._data, status: response.status }))
    .catch((error) => ({ status: error?.response?.status || 500, data: error?.response?._data || undefined }))
```

**Comment by leccyril** [comment]
status is undefined when fetch could not reach the end so i understand why you put the 500 if no status.. ok it is working now...

i think i missed the response between status and error object...

**Comment by adarshmadrecha** [comment]
@leccyril can you close this issue, since your question is answered.

**Comment by trandaison** [comment]
If the request could not reach the Server, there are 2 cases:
- No internet connection.
- Bat gateway 502.
How to how to determine the case?
